services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: civeso
      POSTGRES_PASSWORD: civeso
    ports:
      - '5432:5432'
  events:
    image: events-service:0.0.1-SNAPSHOT
    depends_on:
      - postgres
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - '8081:8081'
  registrations:
    image: registration-service:0.0.1-SNAPSHOT
    depends_on:
      - postgres
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - '8080:8080'