### Create a new registration

POST localhost:8080/registrations
Content-Type: application/json

{"productId": 801, "attendeeName": "Maxi"}

//Get status of application
GET localhost:8080/actuator/health

GET localhost:8080/actuator/env
GET localhost:8080/actuator/beans
GET localhost:8080/actuator/conditions
GET localhost:8080/actuator/mappings
GET localhost:8080/actuator/loggers

GET localhost:8080/actuator/metrics